export const GET_ERRORS_AUTH = "GET_ERRORS_AUTH";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ALL_CENTERS = "GET_ALL_CENTERS"
export const GET_SINGLE_CENTER = "GET_SINGLE_CENTER"

export const GET_ALL_PHARMACIES = "GET_ALL_PHARMACIES"
export const GET_SINGLE_PHARMACIE = "GET_SINGLE_PHARMACIE"


export const GET_ALL_VACCINS = "GET_ALL_VACCINS"
export const GET_SINGLE_VACCIN = "GET_SINGLE_VACCIN"

export const GET_ALL_CITIZENS = "GET_ALL_CITIZENS"
export const GET_SINGLE_CITIZEN = "GET_SINGLE_CITIZEN"


export const GET_ALL_OPERATORS = "GET_ALL_OPERATORS"
export const GET_SINGLE_OPERATOR = "GET_SINGLE_OPERATOR"

export const GET_ALL_OPENDAY = "GET_ALL_OPENDAY"

export const SET_CITIZEN = "SET_CITIZEN";

export const SET_MESSAGE = "SET_MESSAGE"

export const SET_CENTER = "SET_CENTER";
